export const AUTENTICAR_USUARIO = "AUTENTICAR_USUARIO";
export const SUCESSO_AUTENTICACAO = "SUCESSO_AUTENTICACAO";
export const ERRO_AUTENTICACAO = "ERRO_AUTENTICACAO";

export const CADASTRAR_USUARIO = "CADASTRAR_USUARIO";
export const SUCESSO_CADASTRO = "SUCESSO_CADASTRO";
export const ERRO_CADASTRO = "ERRO_CADASTRO";


